#!/bin/bash

LINE='export PATH=./bin:~/bin:$PATH'
FILE=~/.bash_profile
grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"

LINE='export PATH=./bin:~/bin:$PATH'
FILE=~/.zshrc
grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"

exec ${SHELL} -l
