version: '3.0'
services:
  front:
    image: node:12
    container_name: myvid-front
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app/
    working_dir: /usr/src/app
    command: yarn start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development

volumes:
  nodemodules:
    external: true
