version: '3.0'
services:

  server:
    build:
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    depends_on:
      - postgres
      - redis
    container_name: myvid-back
    volumes:
      - ../:/usr/src/app/
    working_dir: /usr/src/app
    command: yarn dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}

  redis:
    image: redis:6-alpine
    container_name: my-ig-redis

  postgres:
    image: postgres:12.2-alpine
    container_name: my-ig-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: ig-pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
