version: '3.0'
services:
  api:
    #hostname: ${API_HOST}
    build:
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    depends_on:
      - postgres
      - redis
    container_name: myvid-back
    volumes:
      - ../:/usr/src/app/
    working_dir: /usr/src/app
    command: yarn dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}

  redis:
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    image: postgres:12.2-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

networks:
  default:
    external:
      name: ${CLIENT_PROJECT_NAME}_${NETWORK_NAME}
