version: '3.5'
services:
  front:
    container_name: front
    build:
      context: ../../
      dockerfile: ./development/docker/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    working_dir: /usr/src/app
    command: tail -f /dev/null
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}

networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge
