version: '3.0'
services:
  front:
    build:
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    volumes:
      #- nodemodules:/usr/src/app/node_modules
      - ../:/usr/src/app/
    working_dir: /usr/src/app
    command: node run.js -t dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}

    networks:
      - ${NETWORK_NAME}

networks:
  net:
    driver: bridge

# volumes:
#   nodemodules:
#     external: true
