version: '3.5'
services:
  front:
    build:
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    volumes:
      #- nodemodules:/usr/src/app/node_modules
      - ../:/usr/src/app/
    working_dir: /usr/src/app
    command: node run.js -t dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}

networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge

# volumes:
#   nodemodules:
#     external: true
